language: node_js

node_js:
  - stable

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - master

cache: yarn

jobs:
  include:
    - stage: install
      script: yarn
      skip_cleanup: true
    - stage: test
      script: yarn test
      skip_cleanup: true
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run semantic-release
      on:
        branch: master

